### ISSUE TITLE
IOS,AOS 빌드문제

### ISSUE THREAD

**Issue by shinsewon** [jiggag/react-native-kakao-maps#19]
안녕하세요. 설치 이후 실행하려는데 IOS와 AOS둘다 빌드를 할 수 없다고 뜹니다.

카카오 앱 키 설정할때, 카카오 네이티브앱 key가 맞는거죠? 네이티브앱 key가 맞다면 제대로 `./android/app/src/main/res/values/strings.xml` 와 `./Info.plist` 에 API를 입력했는데 , 왜 빌드가 안되는지 모르겠습니다.

**Comment by jiggag** [comment]
네 네이티브 앱키 맞습니다

예시 프로젝트에서도 빌드가 안되는건가요? 

어떤 에러메세지가 뜨고 있는지 알려주실 수 있으신가요?

**Comment by shinsewon** [comment]
예시 프로젝트는 따로 하지는 않았고, 새로 프로젝트를 파서 새롭게 진행했습니다.

` //android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 892 file(s) to forward-jetify. Using 12 workers...
info JS server already running.
info Launching emulator...
info Successfully launched emulator.
info Installing the app...
> Task :app:checkDebugDuplicateClasses FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings
34 actionable tasks: 27 executed, 7 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform libDaumMapAndroid.jar to match attributes {artifactType=enumerated-runtime-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/sewon/Desktop/코드/react-native/kakaoMapTest/node_modules/@jiggag/react-native-kakao-maps/android/libs/libDaumMapAndroid.jar.
         > Check failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform libDaumMapAndroid.jar to match attributes {artifactType=enumerated-runtime-classes, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JetifyTransform: /Users/sewon/Desktop/코드/react-native/kakaoMapTest/node_modules/@jiggag/react-native-kakao-maps/android/libs/libDaumMapAndroid.jar.
         > Check failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 8s

    at makeError (/Users/sewon/Desktop/코드/react-native/kakaoMapTest/node_modules/execa/index.js:174:9)
    at /Users/sewon/Desktop/코드/react-native/kakaoMapTest/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async runOnAllDevices (/Users/sewon/Desktop/코드/react-native/kakaoMapTest/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:109:5)
    at async Command.handleAction (/Users/sewon/Desktop/코드/react-native/kakaoMapTest/node_modules/@react-native-community/cli/build/index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
`


`//ios
error Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening kakaoMapTest.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace kakaoMapTest.xcworkspace -configuration Debug -scheme kakaoMapTest -destination id=9CD80D56-7FAD-4F04-AF3E-5C235B11DE70

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: 8b50b16321c3d3b007d016ce24b3bf85
Build description path: /Users/sewon/Library/Developer/Xcode/DerivedData/kakaoMapTest-dbawjeieyathycasyuxlsotonsvo/Build/Intermediates.noindex/XCBuildData/8b50b16321c3d3b007d016ce24b3bf85-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
PhaseScriptExecution Start\ Packager /Users/sewon/Library/Developer/Xcode/DerivedData/kakaoMapTest-dbawjeieyathycasyuxlsotonsvo/Build/Intermediates.noindex/kakaoMapTest.build/Debug-iphonesimulator/kakaoMapTest.build/Script-FD10A7F022414F080027D42C.sh (in target 'kakaoMapTest' from project 'kakaoMapTest')
    cd /Users/sewon/Desktop/코드/react-native/kakaoMapTest/ios
    /bin/sh -c /Users/sewon/Library/Developer/Xcode/DerivedData/kakaoMapTest-dbawjeieyathycasyuxlsotonsvo/Build/Intermediates.noindex/kakaoMapTest.build/Debug-iphonesimulator/kakaoMapTest.build/Script-FD10A7F022414F080027D42C.sh
Connection to localhost port 8081 [tcp/sunproxyadmin] succeeded!
`


위와 같은 에러들이 발생됩니다 ㅠㅠ

**Comment by jiggag** [comment]
이것만으로는 잘 모르겠네요 🤔

- 다른 RN 프로젝트는 빌드가 잘 되고 있나요?
- 경로(`/Users/sewon/Desktop/코드/react-native/kakaoMapTest`)에 한글이 포함되어있는데 영문으로만 설정된 경로에서 다시 해보시겠어요?
- 혹시 코드가 공개된 상태라면 링크 공유 주실 수 있으신가요
