### ISSUE TITLE
Marker 선택 callback 있나요?

### ISSUE THREAD

**Issue by Doyeon-Cho** [jiggag/react-native-kakao-maps#20]
...

**Comment by jiggag** [comment]
[참고: 커스텀 마커 이미지 설정](https://github.com/jiggag/react-native-kakao-maps#%EC%BB%A4%EC%8A%A4%ED%85%80-%EB%A7%88%EC%BB%A4-%EC%9D%B4%EB%AF%B8%EC%A7%80) 으로 마커를 선택하실 수 있습니다
