### ISSUE TITLE
네이티브 모듈이 로드되지 않습니다.

### ISSUE THREAD

**Issue by Siwoo4u** [jiggag/react-native-kakao-maps#24]
설치하고 해봤는데
Invariant Violation: requireNativeComponent: "KakaoMapView" was not found in the UIManager.
에러가 뜨네요 ...
네이티브 모듈을 찾지 못하는거같아요 pod install도 해줬습니다.
expo로 개발중인데 원인을 아실까요?

**Comment by jiggag** [comment]
🤔 클린 빌드를 시도해보셨나요?

**Comment by Siwoo4u** [comment]
클린빌드를 시도해보고 새로운 프로젝트를 하나 만들어서 해당 모듈만 설치하고 테스트해봐도 동일한 증상입니다.
엑스포가 문제인가 싶어 리엑트네이티브만 설치해서 해도 똑같네요.
제 컴퓨터 환경문제인지.. 일단 다른 컴으로 테스트 다시한번 해보겠습니다.
