### ISSUE TITLE
Can't load map on android

### ISSUE THREAD

**Issue by phuongit0301** [jiggag/react-native-kakao-maps#36]
Hi guys
Im using version 0.0.10. When I run on simulator and real devices, the Map can't load, it just show marker like image below. Could you help me about this?

**Comment by phuongit0301** [comment]
Hi @jiggag 
I have followed example but not work for my side. 
<img width="322" alt="Screenshot 2023-03-26 at 18 49 00" src="https://user-images.githubusercontent.com/3425152/227773609-06a40266-aa03-41ca-9ff0-0572976b1a1b.png">

**Comment by jiggag** [comment]
🤔 can you show me the code??? @phuongit0301 @maxtor3569

**Comment by phuongit0301** [comment]
Im following example on library @jiggag 
```

import { KakakoMapView } from '@jiggag/react-native-kakao-maps';

return (
  <KakaoMapView
    markerImageName="customImageName" // 옵션1
    markerImageUrl="https://github.com/jiggag/react-native-kakao-maps/blob/develop/example/custom_image.png?raw=true" // 옵션2
    markerList={[
        {
          lat: 37.59523,
          lng: 127.08600,
          markerName: 'marker'
        },
        {
          lat: 37.59523,
          lng: 127.08705,
          markerName: 'marker2'
        },
    ]}
    width={300}
    height={500}
    centerPoint={{
        lat: 37.59523,
        lng: 127.08600,
    }}
    onChange={(event) => {
      // event.nativeEvent
    }}
  />
);
```

**Comment by jiggag** [comment]
🤔 @phuongit0301  where are you location? (korea, danang..?)

I think KakaoMap is only visible in korea (otherwise you will see a white screen)
