### ISSUE TITLE
Can not hot reload map when markerList has changed

### ISSUE THREAD

**Issue by de2dhvu1** [jiggag/react-native-kakao-maps#39]
I try to useEffect to update markerList data, but map does not reload.
Another solution:
- When updating markerList I will hide the map, then I will show it again after 2s (setTimeout function). Sometimes app crashes but no error show.

Do we have any solution for this

**Comment by jiggag** [comment]
@de2dhvu1 only android?

**Comment by sunjaaa** [comment]
> @de2dhvu1 only android?

yes only android. 
i also tried , cuz im having the same problem

**Comment by de2dhvu1** [comment]
> > @de2dhvu1 only android?
> 
> yes only android. i also tried , cuz im having the same problem

Kakao map only support native platform. If you want to use on React native, you can config local module from kakao map, access and edit code of kakaomap directly

**Comment by jiggag** [comment]
Did this error occur?
- Tried to register two views with the same name KakaoMapView
- Caused by: java.lang.IllegalStateException: Can't change tag of fragment KakaoMapFragment

**Comment by jsh7195** [comment]
중간에 center나 markerList를 state로 변경하게되면 xcode > createMarker 에서 오류가 발생하고 있습니다.

Thread 1: EXC_BAD_ACCESS (code=1, address=0xbcde2d1c0f80)

**Comment by jiggag** [comment]
> 중간에 center나 markerList를 state로 변경하게되면 xcode > createMarker 에서 오류가 발생하고 있습니다.
> 
> Thread 1: EXC_BAD_ACCESS (code=1, address=0xbcde2d1c0f80)

아래쪽 에러 메시지를 더 공유해주실 수 있으신가요?

**Comment by jsh7195** [comment]
@jiggag 
안녕하세요. 

에러브레이크가 강제로 걸렸을때는 
createMarker에서 Thread 1: EXC_BAD_ACCESS (code=1, address=0xbcde2d1c0f80)
이 오류만 나오고 있는 상황입니다.


에러브레이크가 걸리지않으면
 [native] Error setting property 'centerPoint' of KakaoMapView with tag #1437: Exception thrown while executing UI block: -[OS_nw_array countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x60000074a220
2023-10-10 09:56:02.042077+0900 trablah[14863:35435937] [Presentation] Attempt to present <UIViewController: 0x7fd8db124530> on <UIViewController: 0x7fd8e07208f0> (from <UIViewController: 0x7fd8e07208f0>) which is already presenting <RCTModalHostViewController: 0x7fd8d27a6170>.

이런 오류가 발생합니다.

센터값을 계속 바꾸다보면 에러브레이크가 걸립니다.

**Comment by jiggag** [comment]
@jsh7195 

v0.0.12 에서 이슈 수정하였습니다
