### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by haider792** [jiggag/react-native-kakao-maps#9]
Can you please share the usage of the application

**Comment by jiggag** [comment]
```jsx
import KakakoMaps from '@jiggag/react-native-kakao-maps';

...

const onShow = useCallback(() => {
  KakakoMaps.show({
    markerList: [
      {
        markerName: 'Marker1',
        lat: 37.5359,
        lng: 127.005518,
      },
      {
        markerName: 'Marker2',
        lat: 37.5373,
        lng: 127.005515,
      },
    ],
    centerPoint: {
      lat: 37.5359,
      lng: 127.005518,
    },
  });
}, []);

return (
  <Pressable onPress={onShow}>
    <View>...</View>
  </Pressable>
);
```

Is this helpful? 🤔

**Comment by paletti-ayoung** [comment]
Hi, I did with this example, but I got the error which is 'null is not an object. _reactNativeKakaoMpas.default.show'.
Can you please give me whole example code? Thanks.

**Comment by jiggag** [comment]
> Hi, I did with this example, but I got the error which is 'null is not an object. _reactNativeKakaoMpas.default.show'. Can you please share whole example code? Thanks.

@paletti-ayoung [here🙏](https://github.com/jiggag/react-native-kakao-maps/tree/develop/example)

**Comment by paletti-ayoung** [comment]
감사합니다. 
예제 프로젝트를 보고 해봐도 안되서 그러는데ㅠㅠ
show 함수에서 marker를 찍지않고 그냥 보여줄 수는 없나요?
주신예제대로 복붙해봐도 안드로이드에서는 버튼을 누르면 바로 꺼집니다..ㅠㅠ
혹시 다른 해결책이 있을까요ㅠㅠ

**Comment by jiggag** [comment]
@paletti-ayoung  혹시 `markerList`를 아예 넘기지 않으신건가요?
현재 `markerList`가 필수라서 이걸 넘기지 않은 상태라면 오류가 발생할 것으로 확인됩니다

만약 마커가 없는 지도를 띄우고 싶으시다면 `markerList: []`로 넘겨주셔야해요!

**Comment by paletti-ayoung** [comment]
늦었지만 답변 감사합니다!! 
혹시 여기서 따로 지도 위치가 옮겨질때마다 좌표를 받아 올수 있는 함수는 없나요?

**Comment by jiggag** [comment]
@paletti-ayoung 현재 좌표를 가져오는 기능은 포함되어 있지 않습니다

마커를 그리는 목적으로 사용중인 라이브러리라서 좌표를 반환하는 것이 필요하지 않다고 생각했는데,
현재 지도의 중심점을 반환하는 기능은 있어도 좋을 것 같네요 🤔
한번 생각해보겠습니당!

컴포넌트 형식으로 변경하는 작업은 아직 진행중인 상태입니다 🙈

**Comment by paletti-ayoung** [comment]
@jiggag  넵 감사합니다!! 그리고 현재 지도의 zoomLevel를 받아오는것도 같이 있으면 좋을것같아요!
혹시 컴포넌트 형식으로 변경하는 작업은 언제쯤 완성 되는지 여쭤봐도 될까요?

**Comment by jiggag** [comment]
@paletti-ayoung  #23 컴포넌트 형식으로 지도를 그릴 수 있게 되었습니다 🙏

**Comment by paletti-ayoung** [comment]
> @paletti-ayoung #23 컴포넌트 형식으로 지도를 그릴 수 있게 되었습니다 🙏

감사합니다!!!!
